apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-taka
resources:
- ../../base
images:
- name: bobjwalker99/taka
  newName: bobjwalker99/taka
  newTag: "2.4.14"

patches:
 - target:
    kind: HTTPRoute
    name: taka-route
   patch: |-
    - op: replace
      path: /spec/hostnames/0
      value: takaprod.bobjwalker.local 
