apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-taka
resources:
- ../../base
images:
 - name: bobjwalker99/taka-containers
   newName: bobjwalker99/taka-containers
   newTag: "0.1.79.1"

patches:
 - target:
      kind: Ingress
      name: taka-ingress-nginx
   path: taka-ingress-nginx.yaml
