apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: taka-secrets
  literals:
  - homepageDisplay=blah  
  - sumologicUrl=blah
  - environment=Development
  - openFeatureClientId=blah

resources:
- taka-deployment.yaml