apiVersion: v1
kind: Secret
metadata:
  name: taka-secrets
type: Opaque
stringData:
  homepageDisplay: "blah"
  sumologicUrl: "blah"
  instanceUrl: "blah"
  instanceApiKey: "blah"
  environment: "Development"
  openFeatureClientId: "blah"