apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development-taka
resources:
  - ../../base
images:
  - name: bobjwalker99/taka-containers
    newName: bobjwalker99/taka-containers
    newTag: "1.0.0"
patches:
  - target:
      kind: Ingress
      name: taka-ingress-nginx
    path: taka-ingress-nginx.yaml
